app:
  scheduler:
    enable: true
    interval: ${SCHEDULER_INTERVAL}
    force-check-delay: 10s
  bot-url: ${BOT_URL}

spring:
  application:
    name: scrapper
  datasource:
    url: ${POSTGRES_URL}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}


server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
