app:
  telegram-token: ${BOT_TOKEN}
  scrapper-base-url: ${SCRAPPER_BASE_URL}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  level:
    root=DEBUG:
  config: classpath:log4j2-plain.xml


springdoc:
  swagger-ui:
    path: /swagger-ui
    use-root-path: true
  api-docs:
    path: /api-docs
