app:
  telegram-token:
  scrapper-base-url: http://localhost:8080

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  level:
    root=DEBUG:
  config: classpath:log4j2-plain.xml


springdoc:
  info:
    title: Bot API
    version: 1.0.0
    contact:
      name: Vladimir
      url: https://github.com
  swagger-ui:
    path: /swagger-ui
    use-root-path: true
  api-docs:
    path: /api-docs
